var searchData=
[
  ['realtimeprovider',['RealTimeProvider',['../class_core_1_1_real_time_provider.html',1,'Core::RealTimeProvider'],['../class_core_1_1_real_time_provider.html#a41237e4850e50ca37ab834753adf1bec',1,'Core::RealTimeProvider::RealTimeProvider()']]],
  ['redcardmodule',['RedcardModule',['../namespace_redcard_module.html',1,'RedcardModule'],['../class_deelautos_1_1_deelauto.html#a2bac9f276cb0e732497d943352c003b6',1,'Deelautos::Deelauto::redcardModule()']]],
  ['redcarmodule',['RedcarModule',['../class_redcard_module_1_1_redcar_module.html',1,'RedcardModule']]],
  ['redcarmodule_2ecpp',['RedcarModule.cpp',['../_redcar_module_8cpp.html',1,'']]],
  ['redcarmodule_2eh',['RedcarModule.h',['../_redcar_module_8h.html',1,'']]],
  ['redcarscontext',['RedCarsContext',['../class_core_1_1_red_cars_context.html',1,'Core']]],
  ['redcarscontext_2ecpp',['RedCarsContext.cpp',['../_red_cars_context_8cpp.html',1,'']]],
  ['redcarscontext_2eh',['RedCarsContext.h',['../_red_cars_context_8h.html',1,'']]],
  ['redcarscontextimpl',['RedCarsContextImpl',['../class_core_1_1detail_1_1_red_cars_context_impl.html',1,'Core::detail']]],
  ['redcarscontextimpl_3c_20staticdatastore_20_3e',['RedCarsContextImpl&lt; StaticDatastore &gt;',['../class_core_1_1detail_1_1_red_cars_context_impl.html',1,'Core::detail']]],
  ['reservering',['Reservering',['../class_producten_1_1_reservering.html',1,'Producten::Reservering'],['../class_producten_1_1_verhuur.html#a0e48ee694b59f7ce2bb60620dd249336',1,'Producten::Verhuur::reservering()'],['../class_producten_1_1_reservering.html#a118aae96b4c460213a6b098523702103',1,'Producten::Reservering::Reservering()'],['../class_producten_1_1_reservering.html#aa102b51527ec09dc8138c523f0de4860',1,'Producten::Reservering::Reservering(uint32_t beginMoment, uint32_t eindMoment, std::shared_ptr&lt; Klant &gt; &amp;klant, std::shared_ptr&lt; Deelauto &gt; &amp;deelauto, TariefSoortPtr tariefSoort)']]],
  ['reservering_2ecpp',['Reservering.cpp',['../_reservering_8cpp.html',1,'']]],
  ['reservering_2eh',['Reservering.h',['../_reservering_8h.html',1,'']]],
  ['reserveringcontroller',['ReserveringController',['../class_producten_1_1_reservering_controller.html',1,'Producten::ReserveringController'],['../class_producten_1_1_reservering_controller.html#ae5929676979ef84bdde0b338946f304e',1,'Producten::ReserveringController::ReserveringController()']]],
  ['reserveringcontroller_2ecpp',['ReserveringController.cpp',['../_reservering_controller_8cpp.html',1,'']]],
  ['reserveringcontroller_2eh',['ReserveringController.h',['../_reservering_controller_8h.html',1,'']]],
  ['reserveringrepo',['ReserveringRepo',['../class_producten_1_1_reservering_repo.html',1,'Producten::ReserveringRepo&lt; DataStoreType &gt;'],['../class_producten_1_1_reservering_repo.html#a71beb2666e67f0acf12131f4a3b4be81',1,'Producten::ReserveringRepo::ReserveringRepo()']]],
  ['reserveringrepo_2ecpp',['ReserveringRepo.cpp',['../_reservering_repo_8cpp.html',1,'']]],
  ['reserveringrepo_2eh',['ReserveringRepo.h',['../_reservering_repo_8h.html',1,'']]],
  ['reserveringrepo_3c_20staticdatastore_20_3e',['ReserveringRepo&lt; StaticDatastore &gt;',['../class_producten_1_1_reservering_repo.html',1,'Producten']]],
  ['reservermetklantenmoment',['ReserverMetKlantEnMoment',['../struct_producten_1_1_reserver_met_klant_en_moment.html',1,'Producten::ReserverMetKlantEnMoment'],['../struct_producten_1_1_reserver_met_klant_en_moment.html#a41b4eee2a88ccd41786c0e563fb89e73',1,'Producten::ReserverMetKlantEnMoment::ReserverMetKlantEnMoment()']]],
  ['reset',['reset',['../class_redcard_module_1_1_redcar_module.html#a39343907c5e03f305bcdfc98f8c9fa98',1,'RedcardModule::RedcarModule']]]
];
